### ISSUE TITLE
Depending on the gcc version, a warning will occur when executing the make command.

### ISSUE THREAD

**Issue by nuko-yokohama** [ossc-db/pg_plan_advsr#2]
Depending on the gcc version, a warning will occur when executing the make command.
ex. gcc (GCC) 7.3.1

priority:low

```
pg_plan_advsr.c:1854:5: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
pg_plan_advsr.c:1860:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
  appendStringInfo(str, "host=%s port=%s dbname=%s user=%s", pghost, pgport, dbName, login);
  ^~~~~~~~~~~~~~~~
```

**Comment by yamatattsu** [comment]
Thanks for the report.
For now, I'm using gcc 4.8.x. So, I'll check it later. :)

**Comment by yamatattsu** [comment]
I tested it using "gcc 7.3.1" and I couldn't get any error. See below. 
What is your gcc version? I suppose that this issue is based on your environment.

	$ gcc --version
	gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
	Copyright (C) 2017 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

	$ make
	gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fPIC -I/toshiba/pg10_job/include -I. -I./ -I/toshiba/pg10_job/include/postgresql/server -I/toshiba/pg10_job/include/postgresql/internal  -D_GNU_SOURCE   -c -o pg_plan_advsr.o pg_plan_advsr.c
	gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fPIC -I/toshiba/pg10_job/include -I. -I./ -I/toshiba/pg10_job/include/postgresql/server -I/toshiba/pg10_job/include/postgresql/internal  -D_GNU_SOURCE   -c -o pgsp_json.o pgsp_json.c
	gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fPIC -I/toshiba/pg10_job/include -I. -I./ -I/toshiba/pg10_job/include/postgresql/server -I/toshiba/pg10_job/include/postgresql/internal  -D_GNU_SOURCE   -c -o pgsp_json_text.o pgsp_json_text.c
	gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fPIC -shared -o pg_plan_advsr.so pg_plan_advsr.o pgsp_json.o pgsp_json_text.o -L/toshiba/pg10_job/lib -Wl,--as-needed -Wl,-rpath,'/toshiba/pg10_job/lib',--enable-new-dtags  -L/toshiba/pg10_job/lib -lpq
