### ISSUE TITLE
Need Confirmation - Can i use this pg_plan_advsr in Window

### ISSUE THREAD

**Issue by varinderpatwal** [ossc-db/pg_plan_advsr#9]
Hi Team - I will be thankful you guys if i get to know that if i can use pg_plan_advsr in window OS. I am waiting for prompt reply.

**Comment by yamatattsu** [comment]
Hi @varinderpatwal,

Hi Team - I will be thankful you guys if i get to know that if i can use
> pg_plan_advsr in window OS. I am waiting for prompt reply.
>

Unfortunately, we don't have a project file of MSVC to build a
windows binary, so you can't build it now.
If you create the project file, you can use the extension after making the
binary file.

Regards,
Tatsuro Yamada

**Comment by yamatattsu** [comment]
There was no reply, so it is closed.
